# Generated by Django 4.1.7 on 2023-03-28 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pop', '0003_fonte'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fonte',
        ),
        migrations.DeleteModel(
            name='Genero',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
