# Generated by Django 4.1.7 on 2023-03-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pop', '0004_delete_fonte_delete_genero_delete_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quadrinhos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('link', models.URLField()),
                ('descricao', models.TextField()),
                ('status', models.CharField(choices=[('completed', 'Concluído'), ('ongoing', 'Em andamento'), ('hiatus', 'Hiatus')], max_length=30)),
                ('download', models.FileField(upload_to='quadrinhos')),
                ('tipo', models.CharField(choices=[('HQ', 'HQ'), ('Mangá', 'Mangá'), ('Graphic Novel', 'Graphic Novel')], max_length=30)),
            ],
        ),
    ]
