# Generated by Django 4.1.7 on 2023-03-29 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pop', '0006_remove_quadrinhos_download'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quadrinhos',
            name='status',
            field=models.CharField(choices=[('concluído', 'Concluído'), ('em andamento', 'Em andamento'), ('hiatus', 'Hiatus'), ('listado', 'Listado')], max_length=30),
        ),
        migrations.AlterField(
            model_name='quadrinhos',
            name='tipo',
            field=models.CharField(choices=[('HQ', 'HQ'), ('Mangá', 'Mangá'), ('HQ nacional', 'HQ Nacional'), ('Graphic Novel', 'Graphic Novel')], max_length=30),
        ),
    ]
