# Generated by Django 4.1.7 on 2023-04-03 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pop', '0008_livros'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Livros',
        ),
    ]
