# Generated by Django 4.1.7 on 2023-04-04 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pop', '0014_alter_quadrinhos_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='foto',
            field=models.ImageField(upload_to='livros/'),
        ),
    ]
