# Generated by Django 4.1.7 on 2023-04-06 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pop', '0015_alter_livros_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneroEletronico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GeneroFisico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JogosFisicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('foto', models.ImageField(upload_to='')),
                ('descricao', models.TextField()),
                ('status', models.CharField(choices=[('comprado', 'Comprado'), ('a comprar', 'A comprar'), ('listado', 'Listado')], max_length=30)),
                ('genero_fisico', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pop.generofisico')),
            ],
        ),
        migrations.CreateModel(
            name='JogosEletronicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('foto', models.ImageField(upload_to='')),
                ('descricao', models.TextField()),
                ('status', models.CharField(choices=[('concluído', 'Concluído'), ('em andamento', 'Em andamento'), ('hiatus', 'Hiatus'), ('listado', 'Listado')], max_length=30)),
                ('genero_eletronico', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pop.generoeletronico')),
                ('plataforma', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pop.plataforma')),
            ],
        ),
    ]
